### ISSUE TITLE
[BUG] Packer Build - Conflict: Multiple assets emit different content to the same filename

### ISSUE THREAD

**Issue by mrpacman101** [hayes0724/shopify-packer#121]
**Describe the bug**
packer build results in the following error:
```
ERROR in Conflict: Multiple assets emit different content to the same filename ../snippets/script-tags.liquid

ERROR in Conflict: Multiple assets emit different content to the same filename ../snippets/style-tags.liquid

webpack 5.45.1 compiled with 2 errors in 15161 ms
(node:3296) UnhandledPromiseRejectionWarning: Error: Compile errors
    at /Users/pc/.npm-global/lib/node_modules/@hayes0724/shopify-packer/cli/commands/build.js:42:48
    at /Users/pc/.npm-global/lib/node_modules/@hayes0724/shopify-packer/node_modules/webpack/lib/webpack.js:141:8
    at /Users/pc/.npm-global/lib/node_modules/@hayes0724/shopify-packer/node_modules/webpack/lib/HookWebpackError.js:68:3
    at Hook.eval [as callAsync] (eval at create (/Users/pc/.npm-global/lib/node_modules/@hayes0724/shopify-packer/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/pc/.npm-global/lib/node_modules/@hayes0724/shopify-packer/node_modules/tapable/lib/Hook.js:18:14)
    at Cache.shutdown (/Users/pc/.npm-global/lib/node_modules/@hayes0724/shopify-packer/node_modules/webpack/lib/Cache.js:150:23)
    at /Users/pc/.npm-global/lib/node_modules/@hayes0724/shopify-packer/node_modules/webpack/lib/Compiler.js:1140:15
    at Hook.eval [as callAsync] (eval at create (/Users/pc/.npm-global/lib/node_modules/@hayes0724/shopify-packer/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/pc/.npm-global/lib/node_modules/@hayes0724/shopify-packer/node_modules/tapable/lib/Hook.js:18:14)
    at Compiler.close (/Users/pc/.npm-global/lib/node_modules/@hayes0724/shopify-packer/node_modules/webpack/lib/Compiler.js:1133:23)

(Use `node --trace-warnings ...` to show where the warning was created)
(node:3296) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:3296) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

script-tags.liquid:
```

{%- if layout == 'theme' -%}
<script type="text/javascript" src="{{ 'vendor@layout.theme.js' | asset_url }}" defer="defer"></script>
{%- else -%}
<link rel="prefetch" href="{{ 'vendor@layout.theme.js' | asset_url }}" as="script">
{%- endif -%} {%- if layout == 'theme' -%}
<script type="text/javascript" src="{{ 'layout.theme.js' | asset_url }}" defer="defer"></script>
{%- else -%}
<link rel="prefetch" href="{{ 'layout.theme.js' | asset_url }}" as="script">
{%- endif -%} {%- if template == 'cart' -%}
<script type="text/javascript" src="{{ 'template.cart.js' | asset_url }}" defer="defer"></script>
{%- else -%}
<link rel="prefetch" href="{{ 'template.cart.js' | asset_url }}" as="script">
{%- endif -%} {%- if template == 'collection' -%}
<script type="text/javascript" src="{{ 'template.collection.js' | asset_url }}" defer="defer"></script>
{%- else -%}
<link rel="prefetch" href="{{ 'template.collection.js' | asset_url }}" as="script">
{%- endif -%} {%- if template == 'index' -%}
<script type="text/javascript" src="{{ 'template.index.js' | asset_url }}" defer="defer"></script>
{%- else -%}
<link rel="prefetch" href="{{ 'template.index.js' | asset_url }}" as="script">
{%- endif -%} {%- if template == 'page' -%}
<script type="text/javascript" src="{{ 'template.page.js' | asset_url }}" defer="defer"></script>
{%- else -%}
<link rel="prefetch" href="{{ 'template.page.js' | asset_url }}" as="script">
{%- endif -%} {%- if template == 'product' -%}
<script type="text/javascript" src="{{ 'template.product.js' | asset_url }}" defer="defer"></script>
{%- else -%}
<link rel="prefetch" href="{{ 'template.product.js' | asset_url }}" as="script">
{%- endif -%} {%- if template == 'customers/login' -%}
<script type="text/javascript" src="{{ 'template.login.js' | asset_url }}" defer="defer"></script>
{%- else -%}
<link rel="prefetch" href="{{ 'template.login.js' | asset_url }}" as="script">
{%- endif -%} {%- if template == 'customers/register' -%}
<script type="text/javascript" src="{{ 'template.register.js' | asset_url }}" defer="defer"></script>
{%- else -%}
<link rel="prefetch" href="{{ 'template.register.js' | asset_url }}" as="script">
{%- endif -%}

```

style-tags.liquid:
```

{%- if layout == 'theme' -%}
<link type="text/css" href="{{ 'layout.theme.css' | asset_url }}" rel="stylesheet">
{%- else -%}
<link rel="prefetch" href="{{ 'layout.theme.css' | asset_url }}" as="style">
{%- endif -%} {%- if template == 'collection' -%}
<link type="text/css" href="{{ 'template.collection.css' | asset_url }}" rel="stylesheet">
{%- else -%}
<link rel="prefetch" href="{{ 'template.collection.css' | asset_url }}" as="style">
{%- endif -%} {%- if template == 'index' -%}
<link type="text/css" href="{{ 'template.index.css' | asset_url }}" rel="stylesheet">
{%- else -%}
<link rel="prefetch" href="{{ 'template.index.css' | asset_url }}" as="style">
{%- endif -%} {%- if template == 'page' -%}
<link type="text/css" href="{{ 'template.page.css' | asset_url }}" rel="stylesheet">
{%- else -%}
<link rel="prefetch" href="{{ 'template.page.css' | asset_url }}" as="style">
{%- endif -%} {%- if template == 'product' -%}
<link type="text/css" href="{{ 'template.product.css' | asset_url }}" rel="stylesheet">
{%- else -%}
<link rel="prefetch" href="{{ 'template.product.css' | asset_url }}" as="style">
{%- endif -%} {%- if template == 'customers/login' -%}
<link type="text/css" href="{{ 'template.login.css' | asset_url }}" rel="stylesheet">
{%- else -%}
<link rel="prefetch" href="{{ 'template.login.css' | asset_url }}" as="style">
{%- endif -%} {%- if template == 'customers/register' -%}
<link type="text/css" href="{{ 'template.register.css' | asset_url }}" rel="stylesheet">
{%- else -%}
<link rel="prefetch" href="{{ 'template.register.css' | asset_url }}" as="style">
{%- endif -%}

```

**To Reproduce**
1. npm install
2. packer build
3. see error

**Expected behavior**
Expected `packer build` to complete compile.

**Screenshots**

**System (please complete the following information):**
 - OS: [OSX BigSur]
 - Node Version [14.17.3]
 - NPM Version [7.19.1]
 - webpack 5.45.1 
 - webpack-cli 4.6.0
 - dev dependencies
```
  "devDependencies": {
    "@babel/plugin-syntax-dynamic-import": "^7.8.3",
    "@babel/plugin-transform-async-to-generator": "^7.10.4",
    "@babel/plugin-transform-runtime": "^7.10.5",
    "@shopify/babel-preset": "^23.1.0",
    "babel-loader": "^8.2.2",
    "css-loader": "^5.2.0",
    "cssnano": "^4.1.10",
    "cssnano-preset-advanced": "^4.0.7",
    "cssnano-preset-default": "^4.0.7",
    "eslint-plugin-shopify": "^35.1.0",
    "postcss-loader": "^5.2.0",
    "postcss-preset-env": "^6.7.0",
    "prettier": "^2.0.5",
    "sass-loader": "^11.0.1",
    "style-loader": "^2.0.0",
    "stylelint-config-recommended-scss": "^4.2.0",
    "stylelint-config-shopify": "^7.4.0",
    "stylelint-scss": "^3.18.0"
  },
```

**Packer (please complete the following information):**
 - Version [2.2.0]

**Theme (please complete the following information):**
 - [Shopify Packer theme](https://github.com/hayes0724/packer-blank-theme) [True]

**Comment by marioloncarek** [comment]
@mrpacman101 check your snippets if style-tags and script-tags god injected somehow, this was the problem when i received this error. i just deleted this 2 files and it worked

**Comment by mrpacman101** [comment]
@marioloncarek Thanks this solved the issue, somehow i downloaded them...
