### ISSUE TITLE
[BUG-Critical] packer build keeps failing on node enviroment

### ISSUE THREAD

**Issue by mrpacman101** [hayes0724/shopify-packer#135]
**Describe the bug**
I am using a remote docker container with a default node enviroment to run my deployment there. (Buddy.works)
Since a few days the build keeps failing and we are not able to reproduce this issue locally - it is only affected on the build server. I have found some issues after deep diving but i am not sure if they are related because i can only debug this on the remote container. 

I am trying to debug and solve this issue for the past 7 days - it keeps going back to the packer/webpack config - i am just lost here - i also suspected it to be maybe path issue because we have "zero" issues locally on "Mac" or "Windows" computers. 

Only on linux and this node box it makes issues.

**To Reproduce**
1. npm install
2. npm run build

**Expected behavior**
I expect the "packer build" command to exit if an error occurs. 
I expect the packer build command to compile/analyze only my project code "NOT" node_modules! If we analyze also node_modules the headache goes bigger right now. 

**Log Output**
```
packer build
Custom webpack configuration found /buddy/greenforce-v2/prod.config.js
- Compiling...
assets by status 6.14 MiB [cached] 302 assets
ERROR in ./src/styles/templates/collection.scss
Module build failed (from ../../usr/local/lib/node_modules/@hayes0724/shopify-packer/node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ../../usr/local/lib/node_modules/@hayes0724/shopify-packer/node_modules/sass-loader/dist/cjs.js):
SassError: expected "{".
  ╷
1 │ import api from "!../../../../../usr/local/lib/node_modules/@hayes0724/shopify-packer/node_modules/style-loader/dist/runtime/injectStylesIntoStyleTag.js";
  │                                                                                                                                                          ^
  ╵
  src/styles/templates/collection.scss 1:154  root stylesheet
    at processResult (/usr/local/lib/node_modules/@hayes0724/shopify-packer/node_modules/webpack/lib/NormalModule.js:721:19)
    at /usr/local/lib/node_modules/@hayes0724/shopify-packer/node_modules/webpack/lib/NormalModule.js:827:5
    at /usr/local/lib/node_modules/@hayes0724/shopify-packer/node_modules/loader-runner/lib/LoaderRunner.js:399:11
    at /usr/local/lib/node_modules/@hayes0724/shopify-packer/node_modules/loader-runner/lib/LoaderRunner.js:251:18
    at context.callback (/usr/local/lib/node_modules/@hayes0724/shopify-packer/node_modules/loader-runner/lib/LoaderRunner.js:124:13)
    at /usr/local/lib/node_modules/@hayes0724/shopify-packer/node_modules/sass-loader/dist/index.js:54:7
    at Function.call$2 (/usr/local/lib/node_modules/@hayes0724/shopify-packer/node_modules/sass/sass.dart.js:95949:16)
    at _render_closure.call$0 (/usr/local/lib/node_modules/@hayes0724/shopify-packer/node_modules/sass/sass.dart.js:83914:23)
    at Object.Primitives_applyFunction (/usr/local/lib/node_modules/@hayes0724/shopify-packer/node_modules/sass/sass.dart.js:6522:30)
    at Object.Function_apply (/usr/local/lib/node_modules/@hayes0724/shopify-packer/node_modules/sass/sass.dart.js:13852:16)
 @ ./src/scripts/templates/collection.js 11:0-48
ERROR in ./src/styles/templates/customers/login.scss
Module build failed (from ../../usr/local/lib/node_modules/@hayes0724/shopify-packer/node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ../../usr/local/lib/node_modules/@hayes0724/shopify-packer/node_modules/sass-loader/dist/cjs.js):
SassError: expected "{".
  ╷
1 │ import api from "!../../../../../../usr/local/lib/node_modules/@hayes0724/shopify-packer/node_modules/style-loader/dist/runtime/injectStylesIntoStyleTag.js";
  │                                                                                                                                                             ^
  ╵
  src/styles/templates/customers/login.scss 1:157  root stylesheet
    at processResult (/usr/local/lib/node_modules/@hayes0724/shopify-packer/node_modules/webpack/lib/NormalModule.js:721:19)
    at /usr/local/lib/node_modules/@hayes0724/shopify-packer/node_modules/webpack/lib/NormalModule.js:827:5
    at /usr/local/lib/node_modules/@hayes0724/shopify-packer/node_modules/loader-runner/lib/LoaderRunner.js:399:11
    at /usr/local/lib/node_modules/@hayes0724/shopify-packer/node_modules/loader-runner/lib/LoaderRunner.js:251:18
    at context.callback (/usr/local/lib/node_modules/@hayes0724/shopify-packer/node_modules/loader-runner/lib/LoaderRunner.js:124:13)
    at /usr/local/lib/node_modules/@hayes0724/shopify-packer/node_modules/sass-loader/dist/index.js:54:7
    at Function.call$2 (/usr/local/lib/node_modules/@hayes0724/shopify-packer/node_modules/sass/sass.dart.js:95949:16)
    at _render_closure.call$0 (/usr/local/lib/node_modules/@hayes0724/shopify-packer/node_modules/sass/sass.dart.js:83914:23)
    at Object.Primitives_applyFunction (/usr/local/lib/node_modules/@hayes0724/shopify-packer/node_modules/sass/sass.dart.js:6522:30)
    at Object.Function_apply (/usr/local/lib/node_modules/@hayes0724/shopify-packer/node_modules/sass/sass.dart.js:13852:16)
 @ ./src/scripts/templates/customers/login.js 11:0-56
ERROR in ./src/styles/templates/customers/register.scss
Module build failed (from ../../usr/local/lib/node_modules/@hayes0724/shopify-packer/node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ../../usr/local/lib/node_modules/@hayes0724/shopify-packer/node_modules/sass-loader/dist/cjs.js):
SassError: expected "{".
  ╷
1 │ import api from "!../../../../../../usr/local/lib/node_modules/@hayes0724/shopify-packer/node_modules/style-loader/dist/runtime/injectStylesIntoStyleTag.js";
  │                                                                                                                                                             ^
  ╵
  src/styles/templates/customers/register.scss 1:157  root stylesheet
    at processResult (/usr/local/lib/node_modules/@hayes0724/shopify-packer/node_modules/webpack/lib/NormalModule.js:721:19)
    at /usr/local/lib/node_modules/@hayes0724/shopify-packer/node_modules/webpack/lib/NormalModule.js:827:5
    at /usr/local/lib/node_modules/@hayes0724/shopify-packer/node_modules/loader-runner/lib/LoaderRunner.js:399:11
    at /usr/local/lib/node_modules/@hayes0724/shopify-packer/node_modules/loader-runner/lib/LoaderRunner.js:251:18
    at context.callback (/usr/local/lib/node_modules/@hayes0724/shopify-packer/node_modules/loader-runner/lib/LoaderRunner.js:124:13)
    at /usr/local/lib/node_modules/@hayes0724/shopify-packer/node_modules/sass-loader/dist/index.js:54:7
    at Function.call$2 (/usr/local/lib/node_modules/@hayes0724/shopify-packer/node_modules/sass/sass.dart.js:95949:16)
    at _render_closure.call$0 (/usr/local/lib/node_modules/@hayes0724/shopify-packer/node_modules/sass/sass.dart.js:83914:23)
    at Object.Primitives_applyFunction (/usr/local/lib/node_modules/@hayes0724/shopify-packer/node_modules/sass/sass.dart.js:6522:30)
    at Object.Function_apply (/usr/local/lib/node_modules/@hayes0724/shopify-packer/node_modules/sass/sass.dart.js:13852:16)
 @ ./src/scripts/templates/customers/register.js 11:0-59
ERROR in ./src/styles/templates/index.scss
Module build failed (from ../../usr/local/lib/node_modules/@hayes0724/shopify-packer/node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ../../usr/local/lib/node_modules/@hayes0724/shopify-packer/node_modules/sass-loader/dist/cjs.js):
SassError: expected "{".
  ╷
1 │ import api from "!../../../../../usr/local/lib/node_modules/@hayes0724/shopify-packer/node_modules/style-loader/dist/runtime/injectStylesIntoStyleTag.js";
  │                                                                                                                                                          ^
  ╵
  src/styles/templates/index.scss 1:154  root stylesheet
    at processResult (/usr/local/lib/node_modules/@hayes0724/shopify-packer/node_modules/webpack/lib/NormalModule.js:721:19)
    at /usr/local/lib/node_modules/@hayes0724/shopify-packer/node_modules/webpack/lib/NormalModule.js:827:5
    at /usr/local/lib/node_modules/@hayes0724/shopify-packer/node_modules/loader-runner/lib/LoaderRunner.js:399:11
    at /usr/local/lib/node_modules/@hayes0724/shopify-packer/node_modules/loader-runner/lib/LoaderRunner.js:251:18
    at context.callback (/usr/local/lib/node_modules/@hayes0724/shopify-packer/node_modules/loader-runner/lib/LoaderRunner.js:124:13)
    at /usr/local/lib/node_modules/@hayes0724/shopify-packer/node_modules/sass-loader/dist/index.js:54:7
    at Function.call$2 (/usr/local/lib/node_modules/@hayes0724/shopify-packer/node_modules/sass/sass.dart.js:95949:16)
    at _render_closure.call$0 (/usr/local/lib/node_modules/@hayes0724/shopify-packer/node_modules/sass/sass.dart.js:83914:23)
    at Object.Primitives_applyFunction (/usr/local/lib/node_modules/@hayes0724/shopify-packer/node_modules/sass/sass.dart.js:6522:30)
    at Object.Function_apply (/usr/local/lib/node_modules/@hayes0724/shopify-packer/node_modules/sass/sass.dart.js:13852:16)
 @ ./src/scripts/templates/index.js 11:0-43
ERROR in ./src/styles/templates/page.scss
Module build failed (from ../../usr/local/lib/node_modules/@hayes0724/shopify-packer/node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ../../usr/local/lib/node_modules/@hayes0724/shopify-packer/node_modules/sass-loader/dist/cjs.js):
SassError: expected "{".
  ╷
1 │ import api from "!../../../../../usr/local/lib/node_modules/@hayes0724/shopify-packer/node_modules/style-loader/dist/runtime/injectStylesIntoStyleTag.js";
  │                                                                                                                                                          ^
  ╵
  src/styles/templates/page.scss 1:154  root stylesheet
    at processResult (/usr/local/lib/node_modules/@hayes0724/shopify-packer/node_modules/webpack/lib/NormalModule.js:721:19)
    at /usr/local/lib/node_modules/@hayes0724/shopify-packer/node_modules/webpack/lib/NormalModule.js:827:5
    at /usr/local/lib/node_modules/@hayes0724/shopify-packer/node_modules/loader-runner/lib/LoaderRunner.js:399:11
    at /usr/local/lib/node_modules/@hayes0724/shopify-packer/node_modules/loader-runner/lib/LoaderRunner.js:251:18
    at context.callback (/usr/local/lib/node_modules/@hayes0724/shopify-packer/node_modules/loader-runner/lib/LoaderRunner.js:124:13)
    at /usr/local/lib/node_modules/@hayes0724/shopify-packer/node_modules/sass-loader/dist/index.js:54:7
    at Function.call$2 (/usr/local/lib/node_modules/@hayes0724/shopify-packer/node_modules/sass/sass.dart.js:95949:16)
    at _render_closure.call$0 (/usr/local/lib/node_modules/@hayes0724/shopify-packer/node_modules/sass/sass.dart.js:83914:23)
    at Object.Primitives_applyFunction (/usr/local/lib/node_modules/@hayes0724/shopify-packer/node_modules/sass/sass.dart.js:6522:30)
    at Object.Function_apply (/usr/local/lib/node_modules/@hayes0724/shopify-packer/node_modules/sass/sass.dart.js:13852:16)
 @ ./src/scripts/templates/page.js 11:0-42
ERROR in ./src/styles/templates/product.scss
Module build failed (from ../../usr/local/lib/node_modules/@hayes0724/shopify-packer/node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ../../usr/local/lib/node_modules/@hayes0724/shopify-packer/node_modules/sass-loader/dist/cjs.js):
SassError: expected "{".
  ╷
1 │ import api from "!../../../../../usr/local/lib/node_modules/@hayes0724/shopify-packer/node_modules/style-loader/dist/runtime/injectStylesIntoStyleTag.js";
  │                                                                                                                                                          ^
  ╵
  src/styles/templates/product.scss 1:154  root stylesheet
    at processResult (/usr/local/lib/node_modules/@hayes0724/shopify-packer/node_modules/webpack/lib/NormalModule.js:721:19)
    at /usr/local/lib/node_modules/@hayes0724/shopify-packer/node_modules/webpack/lib/NormalModule.js:827:5
    at /usr/local/lib/node_modules/@hayes0724/shopify-packer/node_modules/loader-runner/lib/LoaderRunner.js:399:11
    at /usr/local/lib/node_modules/@hayes0724/shopify-packer/node_modules/loader-runner/lib/LoaderRunner.js:251:18
    at context.callback (/usr/local/lib/node_modules/@hayes0724/shopify-packer/node_modules/loader-runner/lib/LoaderRunner.js:124:13)
    at /usr/local/lib/node_modules/@hayes0724/shopify-packer/node_modules/sass-loader/dist/index.js:54:7
    at Function.call$2 (/usr/local/lib/node_modules/@hayes0724/shopify-packer/node_modules/sass/sass.dart.js:95949:16)
    at _render_closure.call$0 (/usr/local/lib/node_modules/@hayes0724/shopify-packer/node_modules/sass/sass.dart.js:83914:23)
    at Object.Primitives_applyFunction (/usr/local/lib/node_modules/@hayes0724/shopify-packer/node_modules/sass/sass.dart.js:6522:30)
    at Object.Function_apply (/usr/local/lib/node_modules/@hayes0724/shopify-packer/node_modules/sass/sass.dart.js:13852:16)
 @ ./src/scripts/templates/product.js 11:0-45
ERROR in ./src/styles/theme.scss
Module build failed (from ../../usr/local/lib/node_modules/@hayes0724/shopify-packer/node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ../../usr/local/lib/node_modules/@hayes0724/shopify-packer/node_modules/sass-loader/dist/cjs.js):
SassError: expected "{".
  ╷
1 │ import api from "!../../../../usr/local/lib/node_modules/@hayes0724/shopify-packer/node_modules/style-loader/dist/runtime/injectStylesIntoStyleTag.js";
  │                                                                                                                                                       ^
  ╵
  src/styles/theme.scss 1:151  root stylesheet
    at processResult (/usr/local/lib/node_modules/@hayes0724/shopify-packer/node_modules/webpack/lib/NormalModule.js:721:19)
    at /usr/local/lib/node_modules/@hayes0724/shopify-packer/node_modules/webpack/lib/NormalModule.js:827:5
    at /usr/local/lib/node_modules/@hayes0724/shopify-packer/node_modules/loader-runner/lib/LoaderRunner.js:399:11
    at /usr/local/lib/node_modules/@hayes0724/shopify-packer/node_modules/loader-runner/lib/LoaderRunner.js:251:18
    at context.callback (/usr/local/lib/node_modules/@hayes0724/shopify-packer/node_modules/loader-runner/lib/LoaderRunner.js:124:13)
    at /usr/local/lib/node_modules/@hayes0724/shopify-packer/node_modules/sass-loader/dist/index.js:54:7
    at Function.call$2 (/usr/local/lib/node_modules/@hayes0724/shopify-packer/node_modules/sass/sass.dart.js:95949:16)
    at _render_closure.call$0 (/usr/local/lib/node_modules/@hayes0724/shopify-packer/node_modules/sass/sass.dart.js:83914:23)
    at Object.Primitives_applyFunction (/usr/local/lib/node_modules/@hayes0724/shopify-packer/node_modules/sass/sass.dart.js:6522:30)
    at Object.Function_apply (/usr/local/lib/node_modules/@hayes0724/shopify-packer/node_modules/sass/sass.dart.js:13852:16)
 @ ./src/scripts/layout/theme.js 13:0-33
7 ERRORS in child compilations (Use 'stats.children: true' resp. '--stats-children' for more details)
webpack 5.53.0 compiled with 14 errors in 10026 ms
(node:40) UnhandledPromiseRejectionWarning: Error: Compile errors
    at /usr/local/lib/node_modules/@hayes0724/shopify-packer/cli/commands/build.js:42:48
    at /usr/local/lib/node_modules/@hayes0724/shopify-packer/node_modules/webpack/lib/webpack.js:141:8
    at /usr/local/lib/node_modules/@hayes0724/shopify-packer/node_modules/webpack/lib/HookWebpackError.js:68:3
    at Hook.eval [as callAsync] (eval at create (/usr/local/lib/node_modules/@hayes0724/shopify-packer/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/usr/local/lib/node_modules/@hayes0724/shopify-packer/node_modules/tapable/lib/Hook.js:18:14)
    at Cache.shutdown (/usr/local/lib/node_modules/@hayes0724/shopify-packer/node_modules/webpack/lib/Cache.js:150:23)
    at /usr/local/lib/node_modules/@hayes0724/shopify-packer/node_modules/webpack/lib/Compiler.js:1147:15
    at Hook.eval [as callAsync] (eval at create (/usr/local/lib/node_modules/@hayes0724/shopify-packer/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/usr/local/lib/node_modules/@hayes0724/shopify-packer/node_modules/tapable/lib/Hook.js:18:14)
    at Compiler.close (/usr/local/lib/node_modules/@hayes0724/shopify-packer/node_modules/webpack/lib/Compiler.js:1140:23)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:40) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:40) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Build finished successfully!
```

**System (please complete the following information):**
 - OS: Node 14.17.3
 - Node Version 14.17.3
 - NPM Version 7.19.1

**Packer (please complete the following information):**
 - Version (latest)

**Comment by mrpacman101** [comment]
Found the issue its not related with packer.
