### ISSUE TITLE
Error: Cannot find module  project_path\packer.env.json

### ISSUE THREAD

**Issue by molotow11** [hayes0724/shopify-packer#21]
Hello,

I'm on Windows 10 and I have this error after "packer init folder" success command.
This for any command, like: packer theme:create --name=sample-theme-name
Also, the same for: "packer start" command
config.json credentials added.
Please, can you help with it?

`
d:\Work\Test>packer theme:create --name=sample-theme-name
(node:15208) UnhandledPromiseRejectionWarning: Error: Cannot find module 'd:\Work\Test\packer.env.json'
Require stack:
- C:\Users\Андрей\AppData\Roaming\npm\node_modules\@hayes0724\shopify-packer\src\env\index.js
- C:\Users\Андрей\AppData\Roaming\npm\node_modules\@hayes0724\shopify-packer\src\theme\index.js
- C:\Users\Андрей\AppData\Roaming\npm\node_modules\@hayes0724\shopify-packer\cli\commands\theme.js
- C:\Users\Андрей\AppData\Roaming\npm\node_modules\@hayes0724\shopify-packer\cli\index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at assign (C:\Users\Андрей\AppData\Roaming\npm\node_modules\@hayes0724\shopify-packer\src\env\index.js:22:15)
    at module.exports (C:\Users\Андрей\AppData\Roaming\npm\node_modules\@hayes0724\shopify-packer\cli\commands\theme.js:12:3)
    at Object.<anonymous> (C:\Users\Андрей\AppData\Roaming\npm\node_modules\@hayes0724\shopify-packer\cli\index.js:45:32)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
(node:15208) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:15208) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

**Comment by hayes0724** [comment]
Make sure you are using the latest packer. The new version uses a file called `packer.env.json` 

```
{
    "development": {
      "id": "74500041118",
      "password": "ebd6ce7f27aae8cdafb8111a5b887b9",
      "store": "my-store-name.myshopify.com",
      "ignore": [
        "settings_data.json"
      ]
    }
}
```
